### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by multiplehats** [deargonaut/paypal-csv-to-mt940#1]
Hey,

Sorry to just hijack/jump into your issues but this is really good! 

Would be great to get some additional info on how to use it. This is something I've been trying to set up for a while. 

I noticed you're using composer etc. I'm pretty used to using that. Which command are you running in the terminal to parse the CSV? 

I'm not a coder, but I can read a bit of php hence the question.

Chris

**Comment by deargonaut** [comment]
Hi @chrisschwartze,

Thanks for your interest.
The code is not really production ready, nor beta, but you can use it. Check the '[tests/native/test.php](https://github.com/deargonaut/paypal-csv-to-mt940/blob/master/tests/native/test.php)' file. And then run via command line or something.
`$> php test.php`

I would suggest just download  / clone the repo because composer in this case will not help you really. But you can do: `composer require deargonaut/paypal-csv-to-mt940`

Good luck.
